import json
import os

data = {
  "generated_at": "2026-08-20 08:00:00",
  "parlays": {
    "today_consensus": {
      "id": "PARLAY-TODAY-01",
      "title": "Combinada #1: Consenso Seguridad Tripartita",
      "subtitle": "1 Selección Élite por Plataforma (Europa League + Libertadores + Conference League)",
      "totalOdds": 4.12,
      "fairOdds": 3.25,
      "cumulativeConfidence": 58.5,
      "combinedEv": "+26.8%",
      "recommendedStake": "1.5% – 2.0% Bankroll",
      "riskLevel": "BAJO - MODERADO",
      "riskBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "legs": [
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "Benfica vs. Aarhus AGF",
          "tournament": "UEFA Europa League (Play-offs)",
          "selection": "Benfica Ganador (-1.5 Hándicap)",
          "odds": 1.58,
          "fairOdds": 1.48,
          "confidencePct": 86,
          "evEdge": "+6.8%",
          "algorithm": "API-Football Dominance Rating (2.90 vs 0.40 xG proyectado en Da Luz)"
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "LDU Quito vs. Mirassol FC",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "LDU Quito Ganador (1)",
          "odds": 1.58,
          "fairOdds": 1.48,
          "confidencePct": 84,
          "evEdge": "+6.5%",
          "algorithm": "Sportmonks Altitude-Adjusted Model (2,850m altitud con 64.5% prob. justa)"
        },
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "SC Corinthians vs. Rosario Central",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "Menos de 2.5 Goles (Under)",
          "odds": 1.65,
          "fairOdds": 1.55,
          "confidencePct": 81,
          "evEdge": "+5.8%",
          "algorithm": "Scores24 Defensive Block & Slow Tempo Index (<1.10 goles/partido)"
        }
      ]
    },
    "today_highyield": {
      "id": "PARLAY-TODAY-02",
      "title": "Combinada #2: Rendimiento & Goles Tripartita",
      "subtitle": "1 Selección Ofensiva por Plataforma (Multiplicador de Alto Rendimiento)",
      "totalOdds": 5.11,
      "fairOdds": 3.90,
      "cumulativeConfidence": 50.2,
      "combinedEv": "+31.2%",
      "recommendedStake": "0.75% – 1.0% Bankroll",
      "riskLevel": "MODERADO",
      "riskBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "legs": [
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "Trabzonspor vs. Ferencváros",
          "tournament": "UEFA Europa League (Play-offs)",
          "selection": "Más de 2.5 Goles Totales (Over)",
          "odds": 1.72,
          "fairOdds": 1.60,
          "confidencePct": 83,
          "evEdge": "+7.4%",
          "algorithm": "Scores24 Fast-Pace Index (78% de partidos de ambos superan 2.5G)"
        },
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "FC Sion vs. AFC Ajax",
          "tournament": "UEFA Conference League (Play-offs)",
          "selection": "Ajax Ganador (2) + Más 1.5 Goles",
          "odds": 1.65,
          "fairOdds": 1.53,
          "confidencePct": 82,
          "evEdge": "+7.9%",
          "algorithm": "API-Football Attack Efficiency (Ajax promedia 2.4 goles/juego europeo)"
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "Beşiktaş vs. Kauno Žalgiris",
          "tournament": "UEFA Europa League (Play-offs)",
          "selection": "Beşiktaş Ganador (1) + Más 2.5 Goles",
          "odds": 1.80,
          "fairOdds": 1.65,
          "confidencePct": 80,
          "evEdge": "+8.6%",
          "algorithm": "Sportmonks Power Rating (Beşiktaş invicto en Tüpraş Stadyumu con +2.1 xG)"
        }
      ]
    },
    "today_global_highreturn": {
      "id": "PARLAY-TODAY-03",
      "title": "Combinada #3: Mega Retorno Global Tripartita",
      "subtitle": "Estrategia de Alto Retorno: 3 Mercados de Alta Cuota y Disparidad Técnica Extrema",
      "totalOdds": 16.78,
      "fairOdds": 11.60,
      "cumulativeConfidence": 32.8,
      "combinedEv": "+44.5%",
      "recommendedStake": "0.5% Bankroll",
      "riskLevel": "ALTO RENDIMIENTO / MULTIPLICADOR",
      "riskBadgeClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "legs": [
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "Atalanta vs. Hapoel Tel Aviv",
          "tournament": "UEFA Conference League (Play-offs)",
          "selection": "Atalanta Ganador (-2.0 Hándicap Asiático)",
          "odds": 2.35,
          "fairOdds": 1.98,
          "confidencePct": 72,
          "evEdge": "+18.4%",
          "algorithm": "Scores24 High Press Metric: Atalanta gana por 3+ goles en el 70% de duelos eliminatorios en Bérgamo."
        },
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "LDU Quito vs. Mirassol FC",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "LDU Quito Ganador a Cero (Win to Nil)",
          "odds": 2.55,
          "fairOdds": 2.10,
          "confidencePct": 69,
          "evEdge": "+21.5%",
          "algorithm": "API-Football Clean Sheet Model: Mirassol genera apenas 0.35 xG en altitud; LDU valla invicta en 4/5 juegos coperos."
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "Beşiktaş vs. Kauno Žalgiris",
          "tournament": "UEFA Europa League (Play-offs)",
          "selection": "Beşiktaş (-2.5 Hándicap Asiático)",
          "odds": 2.80,
          "fairOdds": 2.28,
          "confidencePct": 66,
          "evEdge": "+22.8%",
          "algorithm": "Sportmonks Qualitative Disparity: Diferencial de plantilla superior a 15x; Kauno concede 2.8 goles en visitas UEFA."
        }
      ]
    },
    "tomorrow_consensus": {
      "id": "PARLAY-TOMORROW-01",
      "title": "Combinada Mañana: Consenso Tripartito (21 Ago)",
      "subtitle": "1 Selección por Plataforma (Premier League + La Liga + Liga MX)",
      "totalOdds": 4.47,
      "fairOdds": 3.50,
      "cumulativeConfidence": 56.4,
      "combinedEv": "+27.7%",
      "recommendedStake": "1.0% – 1.5% Bankroll",
      "riskLevel": "BAJO - MODERADO",
      "riskBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "legs": [
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "Arsenal vs. Coventry City",
          "tournament": "Premier League (Jornada 1 Inaugural)",
          "selection": "Arsenal (-1.5 Hándicap Asiático)",
          "odds": 1.52,
          "fairOdds": 1.42,
          "confidencePct": 87,
          "evEdge": "+7.1%",
          "algorithm": "API-Football Opener Dominance: Emirates Stadium con 3.1 xG proyectado vs 0.35 del recién ascendido."
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "FC Juárez vs. Club América",
          "tournament": "Liga MX (Apertura 2026 - J5)",
          "selection": "Club América Ganador (2)",
          "odds": 1.75,
          "fairOdds": 1.60,
          "confidencePct": 82,
          "evEdge": "+9.4%",
          "algorithm": "Sportmonks Historical Head-to-Head: América invicto en el Olímpico Benito Juárez en sus últimas 6 visitas."
        },
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "Real Betis vs. Real Sociedad",
          "tournament": "La Liga EA Sports (Jornada 2)",
          "selection": "Menos de 2.5 Goles (Under)",
          "odds": 1.68,
          "fairOdds": 1.56,
          "confidencePct": 80,
          "evEdge": "+7.7%",
          "algorithm": "Scores24 Tactical Balance: 8 de los últimos 10 duelos directos tuvieron menos de 3 goles totales."
        }
      ]
    }
  },
  "today": [
    {
      "id": "PICK-APIFOOTBALL-01",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "UEFA Europa League (Play-offs)",
      "homeTeam": "Benfica",
      "awayTeam": "Aarhus AGF",
      "matchTime": "13:00 CDMX (21:00 CET)",
      "recommendedMarket": "Benfica (-1.5 Hándicap Asiático)",
      "odds": 1.58,
      "fairOdds": 1.48,
      "confidencePct": 86,
      "evEdge": "+6.8%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "API-Football Dominance: Benfica con 2.90 xG proyectado en Lisboa frente a una defensa danesa vulnerable.",
      "inParlay": "Combinada #1"
    },
    {
      "id": "PICK-SPORTMONKS-01",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "LDU Quito",
      "awayTeam": "Mirassol FC",
      "matchTime": "16:00 CDMX (19:00 ECU)",
      "recommendedMarket": "LDU Quito Ganador (1)",
      "odds": 1.58,
      "fairOdds": 1.48,
      "confidencePct": 84,
      "evEdge": "+6.5%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Sportmonks Altitude Model: La altura de Quito (2,850m) inclina el 64.5% de probabilidad justa a favor del 'Rey de Copas'.",
      "inParlay": "Combinada #1"
    },
    {
      "id": "PICK-SCORES24-01",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "SC Corinthians",
      "awayTeam": "Rosario Central",
      "matchTime": "18:30 CDMX (21:30 BRA)",
      "recommendedMarket": "Menos de 2.5 Goles (Under)",
      "odds": 1.65,
      "fairOdds": 1.55,
      "confidencePct": 81,
      "evEdge": "+5.8%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Scores24 Defensive Block: 0-0 en la ida; ambos equipos promedian menos de 1.1 goles/juego en fases eliminatorias.",
      "inParlay": "Combinada #1"
    },
    {
      "id": "PICK-SCORES24-02",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "UEFA Europa League (Play-offs)",
      "homeTeam": "Trabzonspor",
      "awayTeam": "Ferencváros",
      "matchTime": "12:00 CDMX (20:00 TRT)",
      "recommendedMarket": "Más de 2.5 Goles Totales",
      "odds": 1.72,
      "fairOdds": 1.60,
      "confidencePct": 83,
      "evEdge": "+7.4%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Scores24 Fast-Pace Index: 78% de los juegos de Trabzonspor en Turquía han superado los 2.5 goles.",
      "inParlay": "Combinada #2"
    },
    {
      "id": "PICK-APIFOOTBALL-02",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "UEFA Conference League (Play-offs)",
      "homeTeam": "FC Sion",
      "awayTeam": "AFC Ajax",
      "matchTime": "13:30 CDMX (21:30 CET)",
      "recommendedMarket": "Ajax Ganador (2) + Más 1.5 Goles",
      "odds": 1.65,
      "fairOdds": 1.53,
      "confidencePct": 82,
      "evEdge": "+7.9%",
      "riskLevel": "MODERADO",
      "riskClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "keyDriver": "API-Football Offensive Matrix: Ajax promedia 2.4 goles por juego europeo frente a una zaga helvética permisiva.",
      "inParlay": "Combinada #2"
    },
    {
      "id": "PICK-SPORTMONKS-02",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "UEFA Europa League (Play-offs)",
      "homeTeam": "Beşiktaş",
      "awayTeam": "Kauno Žalgiris",
      "matchTime": "12:00 CDMX (20:00 TRT)",
      "recommendedMarket": "Beşiktaş Ganador + Más 2.5 Goles",
      "odds": 1.80,
      "fairOdds": 1.65,
      "confidencePct": 80,
      "evEdge": "+8.6%",
      "riskLevel": "MODERADO",
      "riskClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "keyDriver": "Sportmonks Home Efficiency: Beşiktaş invicto en Estambul con +2.1 xG de diferencial.",
      "inParlay": "Combinada #2"
    },
    {
      "id": "PICK-SCORES24-03",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "UEFA Conference League (Play-offs)",
      "homeTeam": "Atalanta",
      "awayTeam": "Hapoel Tel Aviv",
      "matchTime": "13:00 CDMX (21:00 CET)",
      "recommendedMarket": "Atalanta (-2.0 Hándicap Asiático)",
      "odds": 2.35,
      "fairOdds": 1.98,
      "confidencePct": 72,
      "evEdge": "+18.4%",
      "riskLevel": "ALTO VALOR",
      "riskClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "keyDriver": "Scores24 High Press Model: Atalanta genera 3.2 xG en Bérgamo; victoria por 3+ goles en el 70% de eliminatorias.",
      "inParlay": "Combinada #3 (Mega Retorno)"
    },
    {
      "id": "PICK-APIFOOTBALL-03",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "LDU Quito",
      "awayTeam": "Mirassol FC",
      "matchTime": "16:00 CDMX (19:00 ECU)",
      "recommendedMarket": "LDU Quito Ganador a Cero (Win to Nil)",
      "odds": 2.55,
      "fairOdds": 2.10,
      "confidencePct": 69,
      "evEdge": "+21.5%",
      "riskLevel": "ALTO VALOR",
      "riskClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "keyDriver": "API-Football Clean Sheet Rating: Mirassol con 0.35 xG en altitud; LDU valla invicta en 4 de 5 partidos coperos.",
      "inParlay": "Combinada #3 (Mega Retorno)"
    },
    {
      "id": "PICK-SPORTMONKS-03",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "UEFA Europa League (Play-offs)",
      "homeTeam": "Beşiktaş",
      "awayTeam": "Kauno Žalgiris",
      "matchTime": "12:00 CDMX (20:00 TRT)",
      "recommendedMarket": "Beşiktaş (-2.5 Hándicap Asiático)",
      "odds": 2.80,
      "fairOdds": 2.28,
      "confidencePct": 66,
      "evEdge": "+22.8%",
      "riskLevel": "ALTO VALOR",
      "riskClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "keyDriver": "Sportmonks Disparity Index: Desbalance técnico masivo; Kauno concede 2.8 goles en promedio en visitas europeas.",
      "inParlay": "Combinada #3 (Mega Retorno)"
    }
  ],
  "tomorrow": [
    {
      "id": "PICK-APIFOOTBALL-TOM-01",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "Premier League (Jornada 1 Inaugural)",
      "homeTeam": "Arsenal",
      "awayTeam": "Coventry City",
      "matchTime": "13:00 CDMX (20:00 BST)",
      "recommendedMarket": "Arsenal (-1.5 Hándicap Asiático)",
      "odds": 1.52,
      "fairOdds": 1.42,
      "confidencePct": 87,
      "evEdge": "+7.1%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "API-Football Opener Dominance: Emirates Stadium presenta 3.1 xG proyectado ante un Coventry debutante.",
      "inParlay": "Combinada Mañana"
    },
    {
      "id": "PICK-SPORTMONKS-TOM-01",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "Liga MX (Apertura 2026 - J5)",
      "homeTeam": "FC Juárez",
      "awayTeam": "Club América",
      "matchTime": "21:00 CDMX (21:00 Local)",
      "recommendedMarket": "Club América Ganador (2)",
      "odds": 1.75,
      "fairOdds": 1.60,
      "confidencePct": 82,
      "evEdge": "+9.4%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Sportmonks Head-to-Head: América invicto en sus últimas 6 visitas a Ciudad Juárez con 78% de posesión efectiva.",
      "inParlay": "Combinada Mañana"
    },
    {
      "id": "PICK-SCORES24-TOM-01",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "La Liga EA Sports (Jornada 2)",
      "homeTeam": "Real Betis",
      "awayTeam": "Real Sociedad",
      "matchTime": "13:30 CDMX (21:30 CET)",
      "recommendedMarket": "Menos de 2.5 Goles (Under)",
      "odds": 1.68,
      "fairOdds": 1.56,
      "confidencePct": 80,
      "evEdge": "+7.7%",
      "riskLevel": "MODERADO",
      "riskClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "keyDriver": "Scores24 Tactical Block: Duelo de posesión cerrada en el Villamarín; 8 de los últimos 10 duelos con menos de 3 goles.",
      "inParlay": "Combinada Mañana"
    }
  ]
}

with open('summary_recommendations.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ summary_recommendations.json updated for August 20, 2026!")
