import json
import os

data = {
  "generated_at": "2026-08-19 15:48:00",
  "parlays": {
    "today_consensus": {
      "id": "PARLAY-TODAY-01",
      "title": "Combinada #1: Consenso Seguridad Tripartita",
      "subtitle": "1 Selección Élite por Plataforma (Máxima Probabilidad y Bajo Riesgo)",
      "totalOdds": 4.43,
      "fairOdds": 3.45,
      "cumulativeConfidence": 55.1,
      "combinedEv": "+28.4%",
      "recommendedStake": "1.5% – 2.0% Bankroll",
      "riskLevel": "BAJO - MODERADO",
      "riskBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "legs": [
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "Celtic FC vs. LASK Linz",
          "tournament": "UEFA Champions League (Play-offs)",
          "selection": "Celtic Ganador (1) + Más 1.5 Goles",
          "odds": 1.68,
          "fairOdds": 1.54,
          "confidencePct": 88,
          "evEdge": "+6.1%",
          "algorithm": "Scores24 Home Fortress & Pressing Index (2.8 goles prom. en Celtic Park)"
        },
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "CR Flamengo vs. Cruzeiro EC",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "Flamengo Ganador (1) / Más 1.5 Goles",
          "odds": 1.65,
          "fairOdds": 1.52,
          "confidencePct": 84,
          "evEdge": "+7.9%",
          "algorithm": "API-Football xG Predictive Model (2.15 vs 0.65 xG proyectado en Maracanã)"
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "Cerro Porteño vs. SE Palmeiras",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "Palmeiras Empate No Acción (DNB 2)",
          "odds": 1.60,
          "fairOdds": 1.48,
          "confidencePct": 82,
          "evEdge": "+6.5%",
          "algorithm": "Sportmonks Bayesian Value Matrix (67.5% probabilidad justa modelada)"
        }
      ]
    },
    "today_highyield": {
      "id": "PARLAY-TODAY-02",
      "title": "Combinada #2: Rendimiento & Goles Tripartita",
      "subtitle": "1 Selección Ofensiva por Plataforma (Multiplicador de Rendimiento Medio)",
      "totalOdds": 5.43,
      "fairOdds": 4.12,
      "cumulativeConfidence": 48.6,
      "combinedEv": "+31.8%",
      "recommendedStake": "0.75% – 1.0% Bankroll",
      "riskLevel": "MODERADO",
      "riskBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "legs": [
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "Colorado Rapids vs. Los Angeles FC",
          "tournament": "Major League Soccer (MLS)",
          "selection": "Más de 2.5 Goles Totales (Over)",
          "odds": 1.65,
          "fairOdds": 1.53,
          "confidencePct": 84,
          "evEdge": "+7.0%",
          "algorithm": "Scores24 Fast-Pace Index (76% de partidos recientes de LAFC superaron 2.5G)"
        },
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "LA Galaxy vs. San Jose Earthquakes",
          "tournament": "Major League Soccer (MLS)",
          "selection": "Ambos Equipos Anotan + Over 2.5",
          "odds": 1.78,
          "fairOdds": 1.62,
          "confidencePct": 82,
          "evEdge": "+8.5%",
          "algorithm": "API-Football Offensive Dominance (Cali Clásico promedia 3.4 xG combinados)"
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "Columbus Crew vs. CF Montréal",
          "tournament": "Major League Soccer (MLS)",
          "selection": "Columbus Crew Ganador (1) + Más 1.5 Goles",
          "odds": 1.85,
          "fairOdds": 1.68,
          "confidencePct": 80,
          "evEdge": "+8.9%",
          "algorithm": "Sportmonks Home Efficiency Rating (Columbus invicto en Lower.com Field)"
        }
      ]
    },
    "today_global_highreturn": {
      "id": "PARLAY-TODAY-03",
      "title": "Combinada #3: Mega Retorno Global Tripartita",
      "subtitle": "Estrategia de Alto Retorno: 3 Mercados de Alta Cuota y Disparidad Técnica Extrema",
      "totalOdds": 15.32,
      "fairOdds": 10.80,
      "cumulativeConfidence": 32.5,
      "combinedEv": "+41.8%",
      "recommendedStake": "0.5% Bankroll",
      "riskLevel": "ALTO RENDIMIENTO / MULTIPLICADOR",
      "riskBadgeClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "legs": [
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "Celtic FC vs. LASK Linz",
          "tournament": "UEFA Champions League (Play-offs)",
          "selection": "Celtic Ganador (-1.5 Hándicap Asiático)",
          "odds": 2.15,
          "fairOdds": 1.85,
          "confidencePct": 74,
          "evEdge": "+16.2%",
          "algorithm": "Scores24 Dominance Metric: Victoria por 2+ goles en el 80% de partidos europeos en casa."
        },
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "CR Flamengo vs. Cruzeiro EC",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "Flamengo Ganador a Cero (Win to Nil)",
          "odds": 2.50,
          "fairOdds": 2.08,
          "confidencePct": 70,
          "evEdge": "+20.1%",
          "algorithm": "API-Football Clean Sheet Model: Cruzeiro genera solo 0.45 xG fuera; Flamengo concedió 0 goles en 5 de 6 juegos."
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "LA Galaxy vs. San Jose Earthquakes",
          "tournament": "Major League Soccer (MLS)",
          "selection": "LA Galaxy Ganador + Ambos Anotan (BTTS)",
          "odds": 2.85,
          "fairOdds": 2.35,
          "confidencePct": 68,
          "evEdge": "+21.2%",
          "algorithm": "Sportmonks High-Yield Correlation: 75% de victorias locales de Galaxy en Cali Clásico tienen ambos anotando."
        }
      ]
    },
    "tomorrow_consensus": {
      "id": "PARLAY-TOMORROW-01",
      "title": "Combinada Mañana: Consenso Tripartito (20 Ago)",
      "subtitle": "1 Selección por Plataforma (Conference League + Copa Libertadores)",
      "totalOdds": 4.04,
      "fairOdds": 3.20,
      "cumulativeConfidence": 54.8,
      "combinedEv": "+26.2%",
      "recommendedStake": "1.0% – 1.5% Bankroll",
      "riskLevel": "BAJO - MODERADO",
      "riskBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "legs": [
        {
          "sourceName": "API-Football",
          "sourceColor": "emerald",
          "badgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
          "match": "Chelsea FC vs. Servette FC",
          "tournament": "UEFA Conference League (Play-offs)",
          "selection": "Chelsea (-1.5 Hándicap Asiático)",
          "odds": 1.55,
          "fairOdds": 1.45,
          "confidencePct": 85,
          "evEdge": "+5.8%",
          "algorithm": "API-Football Dominance & Shot Quality Metric (2.85 vs 0.45 xG proyectado)"
        },
        {
          "sourceName": "Sportmonks",
          "sourceColor": "amber",
          "badgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
          "match": "LDU Quito vs. Mirassol FC",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "LDU Quito Ganador (1)",
          "odds": 1.58,
          "fairOdds": 1.48,
          "confidencePct": 83,
          "evEdge": "+6.2%",
          "algorithm": "Sportmonks Altitude-Adjusted Model (2,850m altitud con 64.5% prob. justa)"
        },
        {
          "sourceName": "Scores24",
          "sourceColor": "cyan",
          "badgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
          "match": "SC Corinthians vs. Rosario Central",
          "tournament": "CONMEBOL Copa Libertadores (8vos)",
          "selection": "Menos de 2.5 Goles (Under)",
          "odds": 1.65,
          "fairOdds": 1.55,
          "confidencePct": 78,
          "evEdge": "+5.2%",
          "algorithm": "Scores24 Defensive Block & Slow Tempo Index (<1.10 goles/partido)"
        }
      ]
    }
  },
  "today": [
    {
      "id": "PICK-SCORES24-01",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "UEFA Champions League (Play-offs)",
      "homeTeam": "Celtic FC",
      "awayTeam": "LASK Linz",
      "matchTime": "13:00 CDMX (21:00 CET)",
      "recommendedMarket": "Celtic Ganador (1) + Más 1.5 Goles",
      "odds": 1.68,
      "fairOdds": 1.54,
      "confidencePct": 88,
      "evEdge": "+6.1%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Scores24 Home Fortress: Celtic promedia 2.8 goles en Glasgow; presión alta asfixiante sobre la zaga austriaca.",
      "inParlay": "Combinada #1"
    },
    {
      "id": "PICK-APIFOOTBALL-01",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "CR Flamengo",
      "awayTeam": "Cruzeiro EC",
      "matchTime": "18:30 CDMX (21:30 BRA)",
      "recommendedMarket": "Flamengo Ganador (1) / Más 1.5 Goles",
      "odds": 1.65,
      "fairOdds": 1.52,
      "confidencePct": 84,
      "evEdge": "+7.9%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "API-Football xG Matrix: Proyección de 2.15 xG local vs 0.65 visitante en el Maracanã tras el 1-1 en la ida.",
      "inParlay": "Combinada #1"
    },
    {
      "id": "PICK-SPORTMONKS-01",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "Cerro Porteño",
      "awayTeam": "SE Palmeiras",
      "matchTime": "16:00 CDMX (19:00 PAR)",
      "recommendedMarket": "Palmeiras Empate No Acción (DNB 2)",
      "odds": 1.60,
      "fairOdds": 1.48,
      "confidencePct": 82,
      "evEdge": "+6.5%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Sportmonks Value Bet Engine: Probabilidad justa modelada del 67.5% vs 62.5% implícito en cuotas.",
      "inParlay": "Combinada #1"
    },
    {
      "id": "PICK-SCORES24-02",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "Major League Soccer (MLS)",
      "homeTeam": "Colorado Rapids",
      "awayTeam": "Los Angeles FC",
      "matchTime": "19:30 CDMX (21:30 EDT)",
      "recommendedMarket": "Más de 2.5 Goles Totales",
      "odds": 1.65,
      "fairOdds": 1.53,
      "confidencePct": 84,
      "evEdge": "+7.0%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Scores24 Fast-Pace Index: 76% de los últimos partidos de LAFC han superado la línea de 2.5 goles totales.",
      "inParlay": "Combinada #2"
    },
    {
      "id": "PICK-APIFOOTBALL-02",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "Major League Soccer (MLS)",
      "homeTeam": "LA Galaxy",
      "awayTeam": "San Jose Earthquakes",
      "matchTime": "20:30 CDMX (22:30 EDT)",
      "recommendedMarket": "Ambos Equipos Anotan + Over 2.5",
      "odds": 1.78,
      "fairOdds": 1.62,
      "confidencePct": 82,
      "evEdge": "+8.5%",
      "riskLevel": "MODERADO",
      "riskClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "keyDriver": "API-Football Offensive Dominance: El Cali Clásico promedia 3.4 xG combinados; zagas con alta tasa de goles concedidos.",
      "inParlay": "Combinada #2"
    },
    {
      "id": "PICK-SPORTMONKS-02",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "Major League Soccer (MLS)",
      "homeTeam": "Columbus Crew",
      "awayTeam": "CF Montréal",
      "matchTime": "17:30 CDMX (19:30 EDT)",
      "recommendedMarket": "Columbus Crew Ganador (1) + Más 1.5 Goles",
      "odds": 1.85,
      "fairOdds": 1.68,
      "confidencePct": 80,
      "evEdge": "+8.9%",
      "riskLevel": "MODERADO",
      "riskClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "keyDriver": "Sportmonks Home Efficiency: Columbus invicto en casa con diferencial de gol de +1.65 por 90 minutos.",
      "inParlay": "Combinada #2"
    },
    {
      "id": "PICK-SCORES24-04",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "UEFA Champions League (Play-offs)",
      "homeTeam": "Celtic FC",
      "awayTeam": "LASK Linz",
      "matchTime": "13:00 CDMX (21:00 CET)",
      "recommendedMarket": "Celtic (-1.5 Hándicap Asiático)",
      "odds": 2.15,
      "fairOdds": 1.85,
      "confidencePct": 74,
      "evEdge": "+16.2%",
      "riskLevel": "ALTO VALOR",
      "riskClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "keyDriver": "Scores24 Disparity Model: Alta probabilidad de victoria por margen de 2 o más goles en Glasgow.",
      "inParlay": "Combinada #3 (Mega Retorno)"
    },
    {
      "id": "PICK-APIFOOTBALL-04",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "CR Flamengo",
      "awayTeam": "Cruzeiro EC",
      "matchTime": "18:30 CDMX (21:30 BRA)",
      "recommendedMarket": "Flamengo Ganador a Cero (Win to Nil)",
      "odds": 2.50,
      "fairOdds": 2.08,
      "confidencePct": 70,
      "evEdge": "+20.1%",
      "riskLevel": "ALTO VALOR",
      "riskClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "keyDriver": "API-Football Defensive Dominance: Cruzeiro con menos de 0.5 xG como visitante en el Maracanã.",
      "inParlay": "Combinada #3 (Mega Retorno)"
    },
    {
      "id": "PICK-SPORTMONKS-04",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "Major League Soccer (MLS)",
      "homeTeam": "LA Galaxy",
      "awayTeam": "San Jose Earthquakes",
      "matchTime": "20:30 CDMX (22:30 EDT)",
      "recommendedMarket": "LA Galaxy Ganador + Ambos Anotan",
      "odds": 2.85,
      "fairOdds": 2.35,
      "confidencePct": 68,
      "evEdge": "+21.2%",
      "riskLevel": "ALTO VALOR",
      "riskClass": "bg-purple-500/15 text-purple-400 border-purple-500/30",
      "keyDriver": "Sportmonks Correlation Index: Alta correlación histórica de triunfo de Galaxy recibiendo gol.",
      "inParlay": "Combinada #3 (Mega Retorno)"
    }
  ],
  "tomorrow": [
    {
      "id": "PICK-APIFOOTBALL-03",
      "sourcePlatform": "API-Football",
      "sourceBadgeClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "tournament": "UEFA Conference League (Play-offs)",
      "homeTeam": "Chelsea FC",
      "awayTeam": "Servette FC",
      "matchTime": "13:00 CDMX (21:00 CET)",
      "recommendedMarket": "Chelsea (-1.5 Hándicap Asiático)",
      "odds": 1.55,
      "fairOdds": 1.45,
      "confidencePct": 85,
      "evEdge": "+5.8%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "API-Football Dominance Rating: Stamford Bridge presenta disparidad técnica. Proyección de 2.85 vs 0.45 de Servette.",
      "inParlay": "Combinada Mañana"
    },
    {
      "id": "PICK-SPORTMONKS-03",
      "sourcePlatform": "Sportmonks",
      "sourceBadgeClass": "bg-amber-500/15 text-amber-400 border-amber-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "LDU Quito",
      "awayTeam": "Mirassol FC",
      "matchTime": "16:00 CDMX (19:00 ECU)",
      "recommendedMarket": "LDU Quito Ganador (1)",
      "odds": 1.58,
      "fairOdds": 1.48,
      "confidencePct": 83,
      "evEdge": "+6.2%",
      "riskLevel": "BAJO",
      "riskClass": "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      "keyDriver": "Sportmonks Altitude Adjusted Model: 2,850 metros de altitud en Quito confieren ventaja matemática con 64.5% de probabilidad.",
      "inParlay": "Combinada Mañana"
    },
    {
      "id": "PICK-SCORES24-03",
      "sourcePlatform": "Scores24",
      "sourceBadgeClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "tournament": "CONMEBOL Copa Libertadores (8vos)",
      "homeTeam": "SC Corinthians",
      "awayTeam": "Rosario Central",
      "matchTime": "18:30 CDMX (21:30 BRA)",
      "recommendedMarket": "Menos de 2.5 Goles (Under)",
      "odds": 1.65,
      "fairOdds": 1.55,
      "confidencePct": 78,
      "evEdge": "+5.2%",
      "riskLevel": "MODERADO",
      "riskClass": "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
      "keyDriver": "Scores24 Defensive Block: Planteamiento hermético en Neo Química Arena; ambos clubes promedian menos de 1.1 goles por juego.",
      "inParlay": "Combinada Mañana"
    }
  ]
}

with open('summary_recommendations.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ summary_recommendations.json updated with 3rd global parlay!")
